//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia.Base {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensagens {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagens() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIC.Persistencia.Base.Mensagens", typeof(Mensagens).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agência é requerido !.
        /// </summary>
        internal static string AGENCIACOMPRA_REQUERIDO {
            get {
                return ResourceManager.GetString("AGENCIACOMPRA_REQUERIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banco é requerido !.
        /// </summary>
        internal static string BANCOCOMPRA_REQUERIDO {
            get {
                return ResourceManager.GetString("BANCOCOMPRA_REQUERIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNPJ é requerido !.
        /// </summary>
        internal static string CNPJCOMPRA_REQUERIDO {
            get {
                return ResourceManager.GetString("CNPJCOMPRA_REQUERIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código da compra é requerido !.
        /// </summary>
        internal static string CODIGOCOMPRA_REQUERIDO {
            get {
                return ResourceManager.GetString("CODIGOCOMPRA_REQUERIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta é requerida !.
        /// </summary>
        internal static string CONTACOMPRA_REQUERIDO {
            get {
                return ResourceManager.GetString("CONTACOMPRA_REQUERIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF Invalido !.
        /// </summary>
        internal static string CPF_INVALIDO {
            get {
                return ResourceManager.GetString("CPF_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF requerido !.
        /// </summary>
        internal static string CPF_REQUERIDO {
            get {
                return ResourceManager.GetString("CPF_REQUERIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição é requerido !.
        /// </summary>
        internal static string DESCRICACOMPRAREJEITAR_REQUERIDO {
            get {
                return ResourceManager.GetString("DESCRICACOMPRAREJEITAR_REQUERIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email requerido!.
        /// </summary>
        internal static string EMAIL_REQUERIDO {
            get {
                return ResourceManager.GetString("EMAIL_REQUERIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do Favorecido é requerido !.
        /// </summary>
        internal static string FAVORECIDOCOMPRA_REQUERIDO {
            get {
                return ResourceManager.GetString("FAVORECIDOCOMPRA_REQUERIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login requerido!.
        /// </summary>
        internal static string LOGIN_REQUERIDO {
            get {
                return ResourceManager.GetString("LOGIN_REQUERIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codigo Requerido !.
        /// </summary>
        internal static string MsgRequeridoCorrespondeCodigo {
            get {
                return ResourceManager.GetString("MsgRequeridoCorrespondeCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNPJ Requerido !.
        /// </summary>
        internal static string MsgRequeridoCorrespondenteCNPJ {
            get {
                return ResourceManager.GetString("MsgRequeridoCorrespondenteCNPJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código consignatária requerido !.
        /// </summary>
        internal static string MsgRequeridoCorrespondenteCodigoConsignataria {
            get {
                return ResourceManager.GetString("MsgRequeridoCorrespondenteCodigoConsignataria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome requerido!.
        /// </summary>
        internal static string NOME_REQUERIDO {
            get {
                return ResourceManager.GetString("NOME_REQUERIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É obrigatório o uso de carácter especial na senha!.
        /// </summary>
        internal static string REGULAR_ESPECIAL_SENHA {
            get {
                return ResourceManager.GetString("REGULAR_ESPECIAL_SENHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É obrigatório o uso de letras na senha!.
        /// </summary>
        internal static string REGULAR_LETRA_SENHA {
            get {
                return ResourceManager.GetString("REGULAR_LETRA_SENHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É obrigatório o uso de numeros na senha!.
        /// </summary>
        internal static string REGULAR_NUMERO_SENHA {
            get {
                return ResourceManager.GetString("REGULAR_NUMERO_SENHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamanho de senha de 8 caracteres é requerido!.
        /// </summary>
        internal static string REGULAR_TAMANHO_SENHA {
            get {
                return ResourceManager.GetString("REGULAR_TAMANHO_SENHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha nova requerida!.
        /// </summary>
        internal static string REQUERIDA_SENHA {
            get {
                return ResourceManager.GetString("REQUERIDA_SENHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha antiga requerida!.
        /// </summary>
        internal static string REQUERIDA_SENHA_ANTIGA {
            get {
                return ResourceManager.GetString("REQUERIDA_SENHA_ANTIGA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informar Saldo é requerido !.
        /// </summary>
        internal static string VALORSALDOCOMPRA_REQUERIDO {
            get {
                return ResourceManager.GetString("VALORSALDOCOMPRA_REQUERIDO", resourceCulture);
            }
        }
    }
}
